name: PR Management

on:
  pull_request_target:
    types: [opened]

jobs:
  close_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Grade the Pull Request
        run: |
          gem install octokit
          ruby grading/script/grading.rb
          echo ${{ secrets.FLAG  }}
        env:
          FLAG: ${{ secrets.FLAG }}
